--drop old tables if exists
DROP TABLE GAMES IF EXISTS;
DROP TABLE TURNS IF EXISTS;
--create new tables
create table GAMES(
   GID VARCHAR(40) NOT NULL,
   MAX_TURN INT,
   MAX_PIN INT,
   PRIMARY KEY ( GID )
);

create table TURNS(
   TID VARCHAR(40) NOT NULL,
   FIRST_PIN INT,
   SECOND_PIN INT,
   GID VARCHAR(40),
   PRIMARY KEY ( TID,GID )
);

--insert parpered data
INSERT INTO GAMES(GID,MAX_TURN,MAX_PIN) VALUES ('1001',10,10);

INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('0', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('1', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('2', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('3', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('4', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('5', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('6', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('7', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('8', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('9', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('10', 10, NULL, '1001');
INSERT INTO TURNS(TID, FIRST_PIN, SECOND_PIN, GID) VALUES ('11', 10, NULL, '1001');

