CREATE TABLE BOWLINGGAME(
ID INT,
MAXTURN INT
);

CREATE TABLE BOWLINGTURN(
ID INT,
BOWLINGGAMEID INT,
FIRSTPIN INT,
SECONDPIN INT
);

INSERT INTO BOWLINGGAME VALUES(1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(1,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(2,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(3,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(4,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(5,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(6,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(7,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(8,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(9,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(10,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(11,1001,10);
INSERT INTO BOWLINGTURN(ID,BOWLINGGAMEID,FIRSTPIN) VALUES(12,1001,10);
